# Exception handling 1

<br>

---

<br>

## 오류를 반환하는 방법

```C#
using System;

public static class FileManager
{
    // File을 복사하고, 복사한 크기를 반환하는 함수
    // 항상 성공한다는 보장을 할 수 없는 함수.
    public static int CopyFile(string srcFileName, string dstFileName)
    {
        // ...
        return 100;
    }
}

class Program
{
    static void Main()
    {
        FileManager.CopyFile("C:\\a.txt", "D:\\b.txt");
    }
}
```

<br>

#### 메소드(함수)가 실패 했음을 호출자에게 알려주는 방법

1. 반환값을 사용해서 오류를 전달
2. out 파라미터를 사용하는 방법
3. 예외를 사용하는 방법

<br>

---

<br>

#### 1. 반환값을 사용해서 전달

* 반환 값과 오류가 모호함
* 오류에 대한 자세한 정보를 알려 줄 수 없음
* 사용자가 함수 실패를 반드시 처리하도록 강제할 수 없음
* 정상적인 흐름의 코드와 오류를 처리하는 코드가 분리되지 않고 섞여 있음

<br>

#### 2. out 파라미터 활용

* 반환 값과 오류의 전달을 분리하자!
  * 메소드의 성공/실패(오류)
    * 메소드의 반환값
  * 연산의 수행 결과
    * out 파라미터 사용
* 장점
  * 함수의 성공 실패 여부와 반환값의 분리
  * 오류에 대해 세부적인 정보를 전달할 수 있음
* 단점
  * 사용자 실패를 반드시 처리하도록 **강제할 수 없음**
  * 정상적인 흐름의 코드와 오류를 처리하는 코드가 분리되지 않음
  * 함수 사용법이 까다로움
* C# 언어에서 접두어가 **Try...** 로 시작하는 메소드가 이 방식을 사용함

```c#
using System;

public static class FileManager
{
    public static bool CopyFile(string srcFileName, string dstFileName, out int len)
    {
        // ...
        len = 100;
        return false;
    }
}

class Program
{
    static void Main()
    {
        int len;
        bool ret = FileManager.CopyFile("C:\\a.txt", "D:\\b.txt", out len);
        if(ret == false)
        {
            // ...
        }
        
        string s = "10";
        int num;
        bool b = int.TryParse(s, out num);
    }
}
```

<br>

#### 3. 예외를 사용하는 방법

* 메소드가 실패하면
  *  `throw` 키워드를 사용해서 예외를 던짐
  * 오류의 전달과 메소드의 반환 값이 **완전히 분리**됨
  * Exception 클래스의 다양한 속성과 메소드 등을 이용해서 오류에 대한 **다양한 정보 전달** 가능

* 메소드에서 예외가 발생할 때
  * 예외를 처리하지 않으면 **오류 메시지 발생 후 프로그램 종료**됨
    * 이를 통해 오류 처리에 강제성을 부여할 수 있음
  * `try ~ catch` 문을 사용해서 오류를 처리.
* 특징
  * 오류 처리에 대한 **강제성**이 생기고
  * 정상적인 흐름의 코드와 **오류 처리를 위한 코드를 분리**할 수 있음

```C#
using System;

public static class FileManager
{
    public static int CopyFile(string srcFileName, string dstFileName)
    {
        // ...
        if( 실패 )
            throw new Exception("파일 접근 권한 없음");
        
        return 100;
    }
}

class Program
{
    static void Main()
    {
        try
        {
        	FileManager.CopyFile("C:\\a.txt", "D:\\b.txt");
            
            Console.WriteLine("기존 파일 삭제");
            Console.WriteLine("신규 파일 삭제");
        }
        catch( Exception e )
        {
            Console.WriteLine(e.Message);
        }
        
        Console.WriteLine("프로그램은 계속 실행");
    }
}
```

<br>

#### 결론 : 오류 전달에 대한 권장사항

* 중요하지 않은 사소한 오류
  * 메소드의 반환 값
* 중요한 오류
  * 예외 사용

<br>

---

<br>

## 예외 처리하는 방법

#### 예시 : `DownloadString()`

```C#
using System;
using System.Net;

class Program
{
    static void Main()
    {
        WebClient wc = new WebClient();
        
        string s = wc.DownloadString("http://www.naver.com");
        
        Console.WriteLine(s);
    }
}
```

* `DownloadString()` 메소드는 3가지의 예외가 발생할 수 있다.
* 이에 대한 예외처리 방법을 아래에서 알아보자~~

<br>

#### 1. 세분화해서 처리

```C#
using System;
using System.Net;

class Program
{
    static void Main()
    {
        try
        {
        	WebClient wc = new WebClient();
            string s = wc.DownloadString("http://www.naver.com");
        	Console.WriteLine(s);
        }
        
        catch(System.ArgumentNullException e)
        {}
        catch(System.Net.WebException e)
        {}
        catch(System.NotSupportedException e)
        {}
        
    }
}
```

<br>

#### 2. 모든 예외를 한번에 처리

```c#
using System;
using System.Net;

class Program
{
    static void Main()
    {
        try
        {
        	WebClient wc = new WebClient();
            string s = wc.DownloadString("http://www.naver.com");
        	Console.WriteLine(s);
        }
        catch(System.Exception e)
        {
            Console.WriteLine("모든 예외를 한번에 처리");
        }
        
    }
}
```

<br>

#### 3. 특정 예외만 따로 빼서 처리

```c#
using System;
using System.Net;

class Program
{
    static void Main()
    {
        try
        {
        	WebClient wc = new WebClient();
            string s = wc.DownloadString("http://www.naver.com");
        	Console.WriteLine(s);
        }
        catch(System.Net.WebException e)
        {
            // 따로 빼서 처리
        }
        catch(System.Exception e)
        {
            Console.WriteLine("모든 예외를 한번에 처리");
        }
        
    }
}
```

* 단, 위에서부터 Exception 처리 하므로 

* `catch(System.Exception e)` 는 맨 마지막에 써주기

<br>

---

<br>

## System.Exception

* 모든 예외 클래스는 `System.Exception` 클래스로부터 파생됨
* `System.Exception`의 주요 멤버 ★★★
  * **`Message`**
    * 예외를 설명하는 문자열
  * **`StackTrace`**
    * 예외의 근원지부터 catch 블록에 도달할 때까지의 모든 메소드에 대한 정보

```C#
using System;

class Program
{
    public static void Goo()
    {
        int[] arr = {1, 2, 3};
        arr[3] = 10; // 예외 발생
    }
    
    public static void Foo()
    {
        Goo();
    }
    
    static void Main()
    {
        try
        {
        	Foo();
        }
        catch(IndexOutOfRangeException e)
        {
            Console.WriteLine(e.Message);
            Console.WriteLine(e.StackTrace);
        }
    }
}
```

<br>

---

<br>

## 발생된 예외를 다시 전달하기

#### 방법

* `throw e`
  * 현재 메소드를 예외의 근원으로 처리
* `throw`
  * 처음 예외가 발생한 메소드를 예외의 근원으로 처리

```C#
using System;

class Server
{
    public void Connect()
    {
        throw new TimeoutException();
    }
}

class Program
{
    static void Foo()
    {
        Server wc = new Server();
        try
        {
            wc.Connect();
        }
        catch (TimeoutException e)
        {
            // 여기서 발생된 예외를
            // Foo()를 호출한 Main()에 알리고 싶으면?
            
            // 방법 1 : 예외의 근원을 이곳으로 보는 방법
            throw e;
            
            // 방법 2 : 좋은 표기법. 예외의 근원을 실제 발생한 곳으로 보는 방법
            trhow; 
        }
    }
    static void Main()
    {
        try
        {
            Foo();
        }
        catch(Exception 3)
        {
            Console.WriteLine(e.StackTrace);
        }
    }
}
```

<br>

---

<br>

## 예외 필터

> `catch (...) when (...)`

* catch 문이 실행된 후 조건을 처리하는 것보다 
* when문을 통해 catch문을 굳이 실행하지 않아도 되는 상황을 더 추가하는 게 
* 성능면에서 더 효율적이다

<br>

#### 1. 한 catch 블록에서 여러 예외 상태를 처리

```C#
using System;
using System.Net;

class Program
{
    static void Main()
    {
        WebClient wc = new WevClient();
        try
        {
            string s = wc.DownloadString("http://wwww.naver.com"); // 예외 발생
        }
        catch (WebException e)
        {
            // 여러 예외 상태를 처리하다 보면 catch 블록 내부의 코드가 길어진다..
            if (e.Status == WebExceptionStatus.NameResolutionFailure)
                Console.WriteLine("URL이 잘못되었습니다.");
            else if (e.Status == WebExceptionStatus.Timeout)
            	Console.WriteLine("시간 초과");
            else
                Console.WriteLine("다른 문제");
        }
        catch (Exception e)
        {
        }
        wc.Dispose();
    }
}
```

<br>

#### 2. 예외 필터 : 여러 예외 상태를 따로 catch문에 나눠서 처리

```C#
using System;
using System.Net;

class Program
{
    static void Main()
    {
        WebClient wc = new WevClient();
        try
        {
            string s = wc.DownloadString("http://wwww.naver.com"); // 예외 발생
        }
        catch (WebException e) when (e.Status == WebExceptionStatus.NameResolutionFailure)
        {
            Console.WriteLine("URL이 잘못되었습니다.");
        }
        catch (WebException e) when (e.Status == WebExceptionStatus.Timeout)
        {  
			Console.WriteLine("시간 초과");
        }
        catch (Exception e)
        {
        }
        wc.Dispose();
    }
}
```

<br>

#### 활용 1 : 로깅용 catch

```c#
using System;
class Server
{
    public void Connect()
    {
        throw new TimeoutException();
    }
}

class Program
{
    static void Foo()
    {
        Server wc = new Server();
        
        try
        {
            wc.Connect();
        }
        
        // 이를 사용하는 이유
        // : catch 자체는 하지 않으나, 로깅만 하려고!
        catch (Exception e) when (Logging(e))
        {
            Console.WriteLine("Foo catch");
        }
    }
    
    static bool Logging(Exception e)
    {
        Console.WriteLine($"LOG : {e.Message}");
        return false; // 로깅만 하기 위해 항상 false를 리턴
    }
    
    static void Main()
    {
        try
        {
            Foo();
        }
        catch (Exception e)
        {
            Console.WriteLine("예외처리");
        }
    }
}
```

<br>

#### 활용 2

```C#
using System;

class Server
{
    public void Connect()
    {
        throw new TimeoutException();
    }
}

class Program
{
    static void Foo()
    {
        int retryCount = 0;
        bool bSuccess = false;
        
        Server wc = new Server();
        
        while(bSuccess == false)
        {
            try
            {
                wc.Connect();
                bSuccess = true;
            }
            
            catch (TimeoutException e) when ( ++retryCount < 4 )
            {
                Console.WriteLine("one more try");
            }

            // 이 방법보다 더 좋은 방법은 바로 위 방법
            /* 
            catch (TimeoutException e)
            {
                // 3번만 접속 시도하도록 설정
                if ( ++retryCount < 4 )
                    Console.WriteLine("one more try");
                else
                    throw;
            }
            */
            
            
        }
    }
    
    static void Main()
    {
        try
        {
            Foo();
        }
        catch (Exception e)
        {
            Console.WriteLine("Main 예외 처리");
        }
    }
}
```

